// 20 Futuristic 3D Games Configuration Database with Real Cover Artworks
export const INITIAL_GAMES = [
  {
    id: 'cyber-runner-3d',
    title: 'Cyber Runner: Pulse',
    category: 'action',
    badge: '3D HIGHWAY',
    image: '/cover-runner.jpg',
    color: '#00f3ff',
    plays: '142.8K',
    rating: '4.9',
    description: 'High-speed 3D infinite runner on a neon cyber freeway. Dodge quantum barriers, jump across cyber grids, and harvest energy cores.',
    controls: 'Arrow Left/Right (or A/D) to steer, Up/Space to Jump, Touch arrows on Mobile',
    playableType: 'threejs-runner',
    difficulty: 'Extreme Speed',
    featured: true,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'space-blaster-3d',
    title: 'Galactic Fury: Starfighter 3D',
    category: 'shooter',
    badge: '3D COCKPIT',
    image: '/cover-space.jpg',
    color: '#9d00ff',
    plays: '112.1K',
    rating: '4.9',
    description: 'First-person starfighter cockpit view in deep space. Lock onto incoming plasma asteroids and cyborg drones with dual pulse lasers.',
    controls: 'Mouse/Touch to Aim, Click/Tap to Fire dual lasers, Space to Shield',
    playableType: 'threejs-blaster',
    difficulty: 'Pro Pilot',
    featured: true,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'neon-tunnel-3d',
    title: 'Neon Tunnel: Warp Speed 3D',
    category: 'racing',
    badge: 'HYPERSPACE',
    image: '/cover-tunnel.jpg',
    color: '#ff007f',
    plays: '98.4K',
    rating: '4.8',
    description: 'Dive into a spiraling hyperspace 3D vortex. Rotate your craft 360° along the tunnel circumference to evade laser barriers at lightspeed.',
    controls: 'Arrow Left/Right (or A/D) to rotate tunnel, Space for nitro hyper-boost',
    playableType: 'threejs-tunnel',
    difficulty: 'Lightspeed',
    featured: true,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'mecha-brawl-arena',
    title: 'Cyber Mech Arena 3D',
    category: 'action',
    badge: 'TITAN BRAWL',
    image: '/cover-mecha.jpg',
    color: '#ff9900',
    plays: '130.4K',
    rating: '4.9',
    description: 'Piloted titan battle mechs clash in a dark neon arena. Wield glowing plasma blades, deploy energy shields, and unleash EMP missiles.',
    controls: 'Arrows / Touch to maneuver, Space / Tap to Slash, Shift for Shield',
    playableType: 'interactive-arena',
    difficulty: 'Hardcore',
    featured: true,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'cyber-pong-3d',
    title: 'Holo-Pong Quantum 3D',
    category: 'action',
    badge: '3D HOCKEY',
    image: '/app-icon.jpg',
    color: '#00ffaa',
    plays: '85.2K',
    rating: '4.7',
    description: 'Holographic sci-fi air hockey against an adaptive quantum AI neural network with curving photon puck physics.',
    controls: 'Mouse / Touch drag paddle across glowing grid table to deflect photon puck',
    playableType: 'threejs-pong',
    difficulty: 'Adaptive AI',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'quantum-matrix-breaker',
    title: 'Quantum Matrix Breaker 3D',
    category: 'puzzle',
    badge: '3D MATRIX',
    image: '/cover-tunnel.jpg',
    color: '#ffe600',
    plays: '74.5K',
    rating: '4.8',
    description: '3D neon isometric brick breaker with multi-ball antimatter powerups and exploding crystalline cyber nodes.',
    controls: 'Move paddle left/right, Space/Tap to launch antimatter ball',
    playableType: 'interactive-arena',
    difficulty: 'Medium',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'hover-drift-3d',
    title: 'Hover Drift Neo-Tokyo 3D',
    category: 'racing',
    badge: 'SKY RACING',
    image: '/hero-banner.jpg',
    color: '#00d4ff',
    plays: '118.3K',
    rating: '4.9',
    description: 'Anti-gravity magnetic hovercar racing along suspended sky-tracks above cyberpunk megalopolis Neo-Tokyo.',
    controls: 'Left/Right to steer hovercraft, Space to engage plasma drift',
    playableType: 'interactive-arena',
    difficulty: 'Extreme',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'holo-sniper-3d',
    title: 'Holo-Sniper: Cyber Overwatch',
    category: 'shooter',
    badge: 'CYBER FPS',
    image: '/cover-space.jpg',
    color: '#ff3366',
    plays: '91.0K',
    rating: '4.8',
    description: 'Precision targeting simulation against cloaked cyber bots across futuristic neon skyscraper rooftops.',
    controls: 'Mouse/Touch aim, Click to zoom scope and discharge railgun',
    playableType: 'interactive-arena',
    difficulty: 'Precision',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'gravity-flip-3d',
    title: 'Gravity Flip: Lab 3D',
    category: 'action',
    badge: 'ZERO-G',
    image: '/cover-runner.jpg',
    color: '#00f3ff',
    plays: '63.9K',
    rating: '4.6',
    description: 'Manipulate zero-gravity fields to flip floor and ceiling while sprinting through an unstable orbital research station.',
    controls: 'Space / Tap screen to instantly invert gravitational axis',
    playableType: 'interactive-arena',
    difficulty: 'Reflex',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'laser-maze-escape',
    title: 'Laser Maze: Cyber Infiltration',
    category: 'puzzle',
    badge: 'STEALTH 3D',
    image: '/hero-banner.jpg',
    color: '#ef4444',
    plays: '52.7K',
    rating: '4.7',
    description: 'Stealth infiltration simulator. Navigate through dynamic moving laser grids and security sentinel bots to extract encrypted data.',
    controls: 'Touch / Arrow keys to dodge security laser sweep',
    playableType: 'interactive-arena',
    difficulty: 'Tactical',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'cyber-snake-3d',
    title: 'Tron Light-Trail 3D',
    category: 'action',
    badge: 'CYBER GRID',
    image: '/cover-tunnel.jpg',
    color: '#10b981',
    plays: '68.0K',
    rating: '4.6',
    description: 'The legendary arcade battle reimagined with glowing light-cycle trails on a high-speed cyber grid.',
    controls: 'Arrow keys or Swipe to turn 90 degrees instantly',
    playableType: 'interactive-arena',
    difficulty: 'Arcade Classic',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'matrix-memory-grid-3d',
    title: 'Matrix Neural Hacker 3D',
    category: 'puzzle',
    badge: 'MIND MATRIX',
    image: '/app-icon.jpg',
    color: '#a855f7',
    plays: '45.1K',
    rating: '4.5',
    description: 'Neural cyberspace memory sequence decryptor. Memorize glowing holographic quantum cubes to crack the mainframe.',
    controls: 'Tap cubes in the memorized quantum sequence',
    playableType: 'interactive-arena',
    difficulty: 'Brain Hacker',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'galactic-defense-tower',
    title: 'Galactic Base Defender 3D',
    category: 'puzzle',
    badge: 'TOWER DEFENSE',
    image: '/cover-space.jpg',
    color: '#3b82f6',
    plays: '77.2K',
    rating: '4.8',
    description: 'Place futuristic Tesla coils, plasma beam turrets, and EMP generators to defend your starbase against alien swarms.',
    controls: 'Tap/Click to deploy plasma turrets along approach lanes',
    playableType: 'interactive-arena',
    difficulty: 'Strategy',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'neon-helix-drop-3d',
    title: 'Neon Helix Drop 3D',
    category: 'action',
    badge: 'HELIX 3D',
    image: '/cover-tunnel.jpg',
    color: '#ec4899',
    plays: '89.4K',
    rating: '4.7',
    description: 'Drop an energy orb through rotating neon helix rings. Avoid hazardous red zones and chain mega combos.',
    controls: 'Drag left/right to rotate the spiral tower cylinder',
    playableType: 'interactive-arena',
    difficulty: 'Addictive',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'quantum-flappy-drone',
    title: 'Cyber Drone Strike 3D',
    category: 'action',
    badge: 'DRONE PILOT',
    image: '/hero-banner.jpg',
    color: '#8b5cf6',
    plays: '104.2K',
    rating: '4.5',
    description: 'Propel an experimental scout drone through oscillating cyber forcefields and electromagnetic pipes.',
    controls: 'Tap / Click / Space to pulse micro-thrusters',
    playableType: 'interactive-arena',
    difficulty: 'Hardcore',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'cyber-blade-dash',
    title: 'Cyber Blade Katana 3D',
    category: 'action',
    badge: 'SYNTH SLICE',
    image: '/cover-mecha.jpg',
    color: '#06b6d4',
    plays: '95.6K',
    rating: '4.9',
    description: 'Slice incoming neon data blocks synchronized to heavy synthwave bass drops with dual cyber katanas.',
    controls: 'Mouse swipe / Touch slash across flying data cubes',
    playableType: 'interactive-arena',
    difficulty: 'Rhythm Slice',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'zero-g-space-lander',
    title: 'Zero-G Orbital Lander 3D',
    category: 'puzzle',
    badge: 'SPACE SIM',
    image: '/cover-space.jpg',
    color: '#6366f1',
    plays: '41.3K',
    rating: '4.6',
    description: 'Realistic zero-gravity physics lander. Fire RCS thrusters to touch down softly on moving asteroid mining stations.',
    controls: 'Left/Right RCS thrusters, Up key for main thrust',
    playableType: 'interactive-arena',
    difficulty: 'Physics Master',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'bio-dome-survival-3d',
    title: 'Bio-Dome Alien Outpost 3D',
    category: 'shooter',
    badge: 'OUTPOST SURVIVAL',
    image: '/cover-mecha.jpg',
    color: '#14b8a6',
    plays: '83.9K',
    rating: '4.8',
    description: 'Defend the last planetary bio-dome greenhouse from toxic alien swarms with deployable automated laser sentries.',
    controls: 'Aim and fire automated laser bursts at oncoming swarms',
    playableType: 'interactive-arena',
    difficulty: 'Wave Survival',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'hyper-bowling-3d',
    title: 'Hyper Plasma Bowling 3D',
    category: 'action',
    badge: 'COSMIC SPORTS',
    image: '/cover-runner.jpg',
    color: '#f59e0b',
    plays: '59.1K',
    rating: '4.7',
    description: 'Futuristic galactic bowling with anti-gravity ramps, plasma pins, and explosive multi-strike energy balls.',
    controls: 'Flick/drag forward to launch plasma bowling orb',
    playableType: 'interactive-arena',
    difficulty: 'Casual Fun',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  },
  {
    id: 'portal-jumper-3d',
    title: 'Quantum Portal Jumper 3D',
    category: 'puzzle',
    badge: 'DIMENSION PORTAL',
    image: '/hero-banner.jpg',
    color: '#d946ef',
    plays: '71.8K',
    rating: '4.8',
    description: 'Mind-bending dimension puzzle. Deploy paired quantum wormholes to manipulate momentum and reach the extraction pad.',
    controls: 'Left Click: Blue Portal, Right Click: Orange Portal',
    playableType: 'interactive-arena',
    difficulty: 'Mind Bender',
    featured: false,
    enabled: true,
    fps: '60 FPS 3D'
  }
];

export const INITIAL_LEADERBOARD = [
  { rank: 1, name: 'CyberViper_X', score: 98450, badge: '👑 Cyber God', avatar: '🐉' },
  { rank: 2, name: 'NeonSamurai', score: 87210, badge: '⚡ Grandmaster', avatar: '⚔️' },
  { rank: 3, name: 'QuantumGamer', score: 76400, badge: '💎 Diamond', avatar: '💠' },
  { rank: 4, name: 'HoloRider', score: 65120, badge: '🔥 Elite', avatar: '🚀' },
  { rank: 5, name: 'ZeroGravity99', score: 58900, badge: '🌟 Pro', avatar: '🪐' },
  { rank: 6, name: 'MatrixGhost', score: 49350, badge: '⚡ Veteran', avatar: '👾' },
  { rank: 7, name: 'SynthRunner', score: 42100, badge: '🕹️ Skilled', avatar: '🤖' }
];

export const INITIAL_CHAT = [
  { user: 'Valkyrie_9', text: 'Anyone up for Cyber Runner highscore challenge?', time: 'Just now', color: '#00f3ff' },
  { user: 'KiroShi_Tech', text: 'Neon Tunnel level 15 speed is insane!! 🤯', time: '1m ago', color: '#ff007f' },
  { user: 'Nova_Blast', text: 'Space Asteroid Blaster has awesome 3D physics!', time: '2m ago', color: '#ffe600' },
  { user: 'GlitchMaster', text: 'Claimed my 500 Cyber Coins from daily quest 😎', time: '3m ago', color: '#00ffaa' }
];
